name: Rijexamen Scraper

on:
  schedule:
    # Draait elke 10 minuten
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check-slots:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dep
        run: pip install requests

      - name: Execute
        env:
          RIJEXAMEN_USER: ${{ secrets.RIJEXAMEN_USER }}
          RIJEXAMEN_PASS: ${{ secrets.RIJEXAMEN_PASS }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python scraper.py
